spike/flow/urls.py
from django.conf.urls import include, url

from .views import oauth, storyboard

urlpatterns = [
    #auth
    url(r'^dropbox-auth-start/?$', oauth.dropbox_auth_start, name='dropbox_auth_start'),
    url(r'^dropbox-auth-finish$', oauth.dropbox_auth_finish, name='dropbox_auth_finish'),
    url(r'^logout$', oauth.logout, name='logout'),

    url(r'^$', storyboard.home, name='home'),
    url(r'^story/(?P<slug>[\w\d]+)$', storyboard.story_detail),
    url(r'^story$', storyboard.story_list),
]

spike/pic/urls.py
from django.conf.urls import include, url

import pic.views as v

urlpatterns = [
    url(r'^$', v.index, name='index'),

    #API
    url(r'^upload-pic/?$', v.upload_pic, name='upload_pic'),
    url(r'^upload-gif/?$', v.upload_gif, name='upload_gif'),
    url(r'^scene$', v.scene_list, name='scene_list'),
    url(r'^scene/(?P<scene_id>[\d]+)/submissions$', v.submission_list, name='submission_list'),

]

spike/spike/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('flow.urls')),
    url(r'^pic/', include('pic.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spike/flow/models.py
from django.db import models
from django.contrib.auth.models import User

class DropboxToken(models.Model):
    user = models.OneToOneField(User,related_name="dbx")
    access_token = models.CharField(max_length=256)

spike/pic/models.py
from django.db import models


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Scene(models.Model):
    # file will be uploaded to MEDIA_ROOT/pic_uploads
    pic = models.ImageField(upload_to ='pic_uploads/',
                            default = 'pic_uploads/None/no-img.jpg')

class Submission(models.Model):

    gif = models.ImageField(upload_to='submission_uploads/gifs/')
    scene = models.ForeignKey(Scene, null=True)

spike/flow/views/storyboard.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render
from dropbox import dropbox


@login_required
def story_list(request):
    context = {}
    app_key = request.user.dbx.access_token
    dbx = dropbox.Dropbox(app_key)

    all_boards = []
    for board in dbx.files_list_folder('/stories/').entries:
        scenes = {}
        submissions = {}
        # import ipdb; ipdb.sset_trace();
        # /story/ad2/scenes/<scene{number}>/(preview|<scene{number}>)
        for scene in dbx.files_list_folder(board.path_lower+'/scenes').entries:
            scene_key = scene.path_lower.split('/')[-1]
            scenes[scene_key] = {'preview_link': get_preview_link(dbx, scene.path_lower),
                                 'scene_frames': []}
            for scene_image in dbx.files_list_folder(scene.path_lower).entries:
                scene_frame_link = dbx.files_get_temporary_link(scene_image.path_lower).link
                scenes[scene_key]['scene_frames'].append(scene_frame_link)

        # /story/ad2/submissions/<submission_name>/<scene{number}>/(preview|render)
        for scene_submission in dbx.files_list_folder(board.path_lower+'/submissions').entries:
            submission_key = scene_submission.path_lower
            # for scene_submission in dbx.files_list_folder(submission.path_lower).entries:
            submissions[submission_key] = {
               'preview_link': get_preview_link(dbx, scene_submission.path_lower),
               'render_frames': []}
            for render_image in dbx.files_list_folder(scene_submission.path_lower+'/renders').entries[::1]:
                render_frame_link = dbx.files_get_temporary_link(render_image.path_lower).link
                submissions[submission_key]['render_frames'].append(render_frame_link)

        board_info = {'name': board.name,
                      'scenes': scenes,
                      'submissions': submissions}
        all_boards.append(board_info)

    context['all_boards'] =  all_boards
    return render(request, 'flow/story_list.html', context=context)


def get_preview_link(dbx, path):
    try:
        return dbx.files_get_temporary_link(path + '/preview.jpg').link
    except Exception:
        pass
    try:
        return dbx.files_get_temporary_link(path + '/preview.png').link
    except Exception:
        return ""

@login_required
def story_detail(request, slug):
    app_key = request.user.dbx.access_token
    dbx = dropbox.Dropbox(app_key)

    context = []
    for scene in dbx.files_list_folder('/stories/'+slug).entries:
        img = dbx.files_get_temporary_link(scene.path_lower +'/preview.jpg').link
        context.append({'image_url': img})

    return render(request, 'flow/story_detail.html', context=context)


def home(request):
    context = {}
    text = "<h3> user: %s </h3> " % request.user
    text += """<a href="%s"> login to dbx </a><br/>""" % reverse('dropbox_auth_start')
    text += """<a href="%s"> logout </a><br/>""" % reverse('logout')

    if request.user.is_authenticated():

        app_key = request.user.dbx.access_token
        dbx = dropbox.Dropbox(app_key)
        text += """<br/> logged with: %s """ % request.session['dbx_oauth']

        for entry in dbx.files_list_folder('').entries:
            text +=" <br/> %s" % entry.name


    # return render(request, 'flow/index.html', context)
    return HttpResponse(text)

spike/pic/views.py
from django import forms
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.views.decorators.http import require_http_methods

from pic.models import Scene, Submission


def index(request):
    return render(request, 'pic/index.html',
                  {'all_pics': Scene.objects.all(),
                   'all_subs': Submission.objects.all()})


class ImageUploadForm(forms.Form):
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

class GifUploadForm(forms.Form):
    gifs = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

@require_http_methods(["POST"])
def upload_pic(request):
    form = ImageUploadForm(request.POST, request.FILES)
    if form.is_valid():
        for file in form.files.getlist('images'):
            m = Scene.objects.create()
            m.pic = file
            m.save()
        return redirect(reverse('index'))

@require_http_methods(["POST"])
def upload_gif(request):
    form = GifUploadForm(request.POST, request.FILES)
    # if form.is_valid():  # form isnt valid?
    for file in form.files.getlist('gifs'):
        m = Submission.objects.create()
        m.scene = Scene.objects.first()
        m.gif = file
        m.save()
    return redirect(reverse('index'))


def scene_list(request):
    scenes = []
    for p in Scene.objects.all():
        scenes.append([{'id': p.id,
                        'url': 'https://localhost:8000/media/' + p.pic.url}])
    return JsonResponse({'scenes': scenes})


def submission_list(request, scene_id):
    submissions = []
    for s in Submission.objects.filter(scene=scene_id):
        submissions.append([{'id': s.id,
                             'gif_url': 'https://localhost:8000/media/' + s.gif.url}])
    return JsonResponse({'submissions': submissions})

spike/flow/templates/flow/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <h3>{{request.user}}</h3>
        <a href="{% url 'dropbox_auth_start' %}"> login via dbx </a>
        <a href="{% url 'logout' %}"> logout </a>


</body>
</html>

spike/flow/templates/flow/story_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Storyboard</title>
</head>
<body>

<div class="container-fluid">
    {% for scene in scenes %}
	<div class="row">
		<div class="col-md-4">

            <img src="{{ scene.image_url}}" height="300px" width="300px">
            <p> {{scene.image_url}}</p>

		</div>

        <div class="col-md-8">
            {% for submission in scene.submissions %}
                <img src="{{ submission.image_url}}" height="256px" width="256px">
               <p> {{submission.image_url}}</p>
            {% endfor %}
		</div>
	</div>
    {% endfor %}
</div>



</body>
</html>

spike/flow/templates/flow/story_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <title>all boards</title>
</head>
<body>

<div class="container">

{% for board in all_boards %}
  <div class="row">
  <div class="col">
  <h1> {{ board.name}}</h1>
  <h2> scenes </h2>
  {% for scene_name, scene_content in board.scenes.items %}
    <p> {{ scene_name }} </p>
    <!--<img src="{{ scene_content.preview_link }}" width="150px" height="100px">-->
    {% for scene_frame_link in scene_content.scene_frames %}
      <img src="{{ scene_frame_link }}" width="150px" height="100px">
    {% endfor %}
  {% endfor %}
  </div>
  <div class="col">
  <h2> submissions </h2>
  {% for sub_scene_name, sub_content in board.submissions.items %}
      <p> {{ sub_scene_name }} </p>
      <img src="{{ sub_content.preview_link }}" width="150px" height="100px">
      {% for render_frame_link in sub_content.render_frames %}
        <img src="{{ render_frame_link }}" width="100px" height="60px">
      {% endfor %}
  {% endfor %}
  </div>
  </div>
{% endfor %}

 <hr>
</div>
</body>
</html>

spike/pic/templates/pic/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html>
    <head lang="{{ request.LANGUAGE_CODE }}">
        <meta charset="UTF-8">
        {% block meta %}{% endblock meta %}
        <title>{% block title %}{% endblock title %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    </head>

    <body>
    <div class="container">
    {% block content %}
    {% endblock content %}
    </div>

     <footer class="footer">

     </footer>

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

    {% block extra_footer_js %}
    {% endblock extra_footer_js %}

    </body>
</html>

spike/pic/templates/pic/index.html
{% extends "pic/base.html" %}
{% load i18n %}
{% load static %}

{% block title %} pic index {% endblock title %}

{% block content %}
<div class="row">
<div class="col">
  <form action="{% url 'upload_pic' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <p>
        <input id="id_images" type="file" class="" name="images" multiple>
    </p>
    <input type="submit" value="Submit" />
</form>
    <form action="{% url 'upload_gif' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <p>
        <input id="id_gifs" type="file" class="" name="gifs" multiple>
    </p>
    <input type="submit" value="Submit" />
</form>
</div>
  <div class="col">
    {% for pic in all_pics %}

        <img src="{{ pic.pic.url }}" width="100" height="100" />
    {% endfor %}
  </div>
    <div class="col" id="subs" >

    {% for sub in all_subs %}

        <img src="{{ sub.gif.url }}" width="100" height="100" />
    {% endfor %}


  </div>

  <button id="showSub"> toggle</button>
</div>

{% endblock content %}

    {% block extra_footer_js %}
  <script>
    $('#subs').toggle()
    $('#showSub').click(function(){
      $('#subs').toggle()
    });
  </script>
    {% endblock extra_footer_js %}